Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -38,12 +38,12 @@ jobs:
 
     - name: Build APK
       run: |
-    cd cordovaApp
-    cordova build android
-    if [ ! -f platforms/android/app/build/outputs/apk/debug/app-debug.apk ]; then
-      echo "APK file not found! Build may have failed."
-      exit 1
-    fi
+        cd cordovaApp
+        cordova build android
+        if [ ! -f platforms/android/app/build/outputs/apk/debug/app-debug.apk ]; then
+          echo "APK file not found! Build may have failed."
+          exit 1
+        fi
 
     - name: Upload APK
       uses: actions/upload-artifact@v3
